CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [SteamId] NVARCHAR(50) NOT NULL, 
    [PersonaName] NVARCHAR(50) NOT NULL, 
    [Avatar] NVARCHAR(255) NOT NULL, 
    [AvatarMedium] NVARCHAR(255) NOT NULL, 
    [AvatarFull] NVARCHAR(255) NOT NULL, 
    [TimeCreatedSteam] DATETIME2 NOT NULL, 
    [TimeCreatedDb] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [LastUpdateDb] DATETIME2 NOT NULL DEFAULT GETDATE()
)